### ISSUE TITLE
PLC address like  DB415,X66.3, how to read ?

### ISSUE THREAD

**Issue by wei1224hf** [chrislo1976/lua-s7iso#1]
Thanks for your share , this lua module is really helpfull .
I installed this on Ubuntu 16.04, with lua 5.3.6, 
but I don't know how to read and write data, the demo code confused me.

for example, PLC address like  DB415,X66.3, how to read it with lua-s7iso module?

**Comment by chrislo1976** [comment]
Hi!

I guess I have to improve the examples...

`local booleanValue = plc:read('DB415.DBX66.3')`

You will get a variable with boolean type (true / false)

**Comment by wei1224hf** [comment]
Thanks , I read it

**Comment by wei1224hf** [comment]
Thanks , it works
