### ISSUE TITLE
How to use this with LUA 5.1?

### ISSUE THREAD

**Issue by wei1224hf** [chrislo1976/lua-s7iso#2]
Thank you for your share,  
and this module worked on LUA 5.3 , 
but my workspace is using LUA 5.1 , 
is there anyway to make it work on 5.1 ?

**Comment by chrislo1976** [comment]
Hi!
It should work, but I never worked with a version < 5.3.
You could test it yourself, just clone the repo an try to compile it with your desired Lua version.

I'm on holiday soon, I will test it then.

**Comment by wei1224hf** [comment]
Thank you for youre replay, 
I found it hard to compile with LUA 5.1, 
lua-s7iso.so need -fPIC with cmake flag, but this flag can't work with lua 5.1, only work with lua 5.3

this is when I try to compile with lua 5.1, 



make
[ 73%] Built target Snap7
[ 78%] Linking CXX shared module lua-s7iso.so
/usr/bin/ld: /usr/local/lib/liblua.a(lapi.o): relocation R_X86_64_32 against `luaO_nilobject_' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/liblua.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
module/CMakeFiles/lua-s7iso.dir/build.make:151: recipe for target 'module/lua-s7iso.so' failed
make[2]: *** [module/lua-s7iso.so] Error 1
CMakeFiles/Makefile2:182: recipe for target 'module/CMakeFiles/lua-s7iso.dir/all' failed
make[1]: *** [module/CMakeFiles/lua-s7iso.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2


and this is when I try to rebuild lua 5.1, I changed the MakeFile , add the -fPIC flag , it can't compile:


`make linux
cd src && make linux
make[1]: Entering directory "/home/gene/lua-5.1.5/src"
make all MYCFLAGS=-DLUA_USE_LINUX -fPIC MYLIBS="-Wl,-E -ldl -lreadline -lhistory -lncurses" 
make[2]: Entering directory "/home/gene/lua-5.1.5/src"
make[2]: PIC: No such file or directory
make[2]: *** No rule to make target 'PIC'.  Stop.
make[2]: Leaving directory "/home/gene/lua-5.1.5/src"
Makefile:99: recipe for target 'linux' failed
make[1]: *** [linux] Error 2
make[1]: Leaving directory "/home/gene/lua-5.1.5/src"
Makefile:56: recipe for target 'linux' failed
make: *** [linux] Error 2

**Comment by wei1224hf** [comment]
after some days, this worked with lua 5.1.5, 
I missed something with the recompile LUA Makfile , fixed it and it worked
